### ISSUE TITLE
Broken function call

### ISSUE THREAD

**Issue by eileenmcnaughton** [compucorp/uk.co.compucorp.manualdirectdebit#246]
I spotted that this extension calls an old function that no longer exists in core (and was never supported to be called from outside of core) in 2 places

Note that the correct process is to create a pending contribution (order) and then call Payment.create. There are still a couple of core functions that call the legacy deprecated function 'transitionComponents' - but we are working to fully remove that function too.

![image](https://user-images.githubusercontent.com/336308/128622742-91547e86-a43c-41fa-850c-731e40ff9baf.png)

**Comment by omarabuhussein** [comment]
Thanks for reporting this @eileenmcnaughton, though just to be clear the current version of this extension calls the deprecated `transitionComponents` not the removed `transitionComponentsWithReturnMessage`, the main problem for us would be is to confirm that we will get the desired output from calling `Payment.create` API same as we get it from `transitionComponents`, but still I agree that it is something that we will need to replace soon, so will create an internal ticket to address it.

**Comment by eileenmcnaughton** [comment]
@omarabuhussein we plan to switch the remaining places is core from calling transition components to payment.create

**Comment by omarabuhussein** [comment]
This is resolved here: https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/253
